part of 'app_pages.dart';

abstract class Routes {
  Routes._();
  static const ON_BOARDING = _Paths.ON_BOARDING;
  static const HOME = _Paths.HOME;
  static const PROFILE = _Paths.PROFILE;
  static const SPLASH = _Paths.SPLASH;
  static const LOGIN = _Paths.LOGIN;
  static const REGISTER = _Paths.REGISTER;
  static const SETTING = _Paths.SETTING;
  static const VERIFICATION = _Paths.VERIFICATION;
  static const INPUT_PERSONALIZATION = _Paths.INPUT_PERSONALIZATION;
  static const VERIFICATIONDONE = _Paths.VERIFICATIONDONE;
  static const PENDING = _Paths.PENDING;
  static const BOTTOM_BAR = _Paths.BOTTOM_BAR;
  static const SIDE_BAR = _Paths.SIDE_BAR;
  static const PAYMENT = _Paths.PAYMENT;
  static const REPORT = _Paths.REPORT;
  static const REPORT_FORM = _Paths.REPORT_FORM;
  static const REPORT_DETAIL = _Paths.REPORT_DETAIL;
  static const SELECT_MAP = _Paths.SELECT_MAP;
  static const INPUT_MAP = _Paths.INPUT_MAP;
  static const EDIT_MAP = _Paths.EDIT_MAP;
  static const EDIT_PROFILE = _Paths.EDIT_PROFILE;
  static const TERMS = _Paths.TERMS;
  static const FAQ = _Paths.FAQ;
  static const PAYMENT_HISTORY = _Paths.PAYMENT_HISTORY;
  static const FAMILY_MEMBER = _Paths.FAMILY_MEMBER;
  static const DETAILS_ANNOUNCEMENT = _Paths.DETAILS_ANNOUNCEMENT;
  static const DETAILS_EVENT = _Paths.DETAILS_EVENT;
  static const EVENT = _Paths.EVENT;
  static const ANNOUNCEMENT = _Paths.ANNOUNCEMENT;
  static const DETAILS_FAMILY = _Paths.DETAILS_FAMILY;
  static const DETAILS_PAYMENT_HISTORY = _Paths.DETAILS_PAYMENT_HISTORY;
  static const REPORT_DANA = _Paths.REPORT_DANA;
  static const NOTIFICATION = _Paths.NOTIFICATION;
  static const DETAIL_NOTIFICATION = _Paths.DETAIL_NOTIFICATION;
  static const EDIT_PASSWORD = _Paths.EDIT_PASSWORD;
  static const RESET_PASSWORD = _Paths.RESET_PASSWORD;
  static const NEW_PASSWORD = _Paths.NEW_PASSWORD;
  static const VERIFICATION_EMAIL = _Paths.VERIFICATION_EMAIL;
  static const EDIT_FAMILY = _Paths.EDIT_FAMILY;
}

abstract class _Paths {
  _Paths._();
  static const ON_BOARDING = '/on-boarding';
  static const HOME = '/home';
  static const PROFILE = '/profile';
  static const SPLASH = '/splash';
  static const LOGIN = '/login';
  static const REGISTER = '/register';
  static const SETTING = '/setting';
  static const VERIFICATION = '/verification';
  static const INPUT_PERSONALIZATION = '/input-personalization';
  static const VERIFICATIONDONE = '/verificationdone';
  static const PENDING = '/pending';
  static const BOTTOM_BAR = '/bottom-bar';
  static const SIDE_BAR = '/side-bar';
  static const PAYMENT = '/payment';
  static const REPORT = '/report';
  static const REPORT_FORM = '/report-form';
  static const REPORT_DETAIL = '/report-detail';
  static const SELECT_MAP = '/select_map';
  static const INPUT_MAP = '/input_map';
  static const EDIT_MAP = '/edit_map';
  static const EDIT_PROFILE = '/edit-profile';
  static const TERMS = '/terms';
  static const FAQ = '/faq';
  static const FAMILY_MEMBER = '/family-member';
  static const DETAILS_ANNOUNCEMENT = '/details-announcement';
  static const DETAILS_EVENT = '/details-event';
  static const EVENT = '/event';
  static const ANNOUNCEMENT = '/announcement';
  static const DETAILS_FAMILY = '/details-family';
  static const DETAILS_PAYMENT_HISTORY = '/details-payment-history';
  static const REPORT_DANA = '/report-dana';
  static const PAYMENT_HISTORY = '/payment-history';
  static const NOTIFICATION = '/notification';
  static const DETAIL_NOTIFICATION = '/detail-notification';
  static const EDIT_PASSWORD = '/edit-password';
  static const RESET_PASSWORD = '/reset-password';
  static const NEW_PASSWORD = '/new-password';
  static const VERIFICATION_EMAIL = '/verification-email';
  static const EDIT_FAMILY = '/edit-family';
}
